// This file is auto-generated by @hey-api/openapi-ts

export const Body_login_get_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-get_access_token'
} as const;

export const CategoryCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 50,
            minLength: 1,
            title: 'Name'
        },
        description: {
            type: 'string',
            maxLength: 200,
            title: 'Description'
        }
    },
    type: 'object',
    required: ['name', 'description'],
    title: 'CategoryCreate'
} as const;

export const CategoryResponseSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        },
        name: {
            type: 'string',
            maxLength: 50,
            minLength: 1,
            title: 'Name'
        },
        description: {
            type: 'string',
            maxLength: 200,
            title: 'Description'
        }
    },
    type: 'object',
    required: ['name', 'description'],
    title: 'CategoryResponse'
} as const;

export const CategoryUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 200
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'CategoryUpdate'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PasswordUpdateSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'PasswordUpdate'
} as const;

export const PaymentMethodSchema = {
    type: 'string',
    enum: ['cash', 'card'],
    title: 'PaymentMethod'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const TransactionCreateSchema = {
    properties: {
        amount: {
            type: 'integer',
            title: 'Amount'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        transaction_date: {
            type: 'string',
            format: 'date-time',
            title: 'Transaction Date'
        },
        transaction_type: {
            '$ref': '#/components/schemas/TransactionType'
        },
        category_id: {
            type: 'integer',
            title: 'Category Id'
        },
        payment_method: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/PaymentMethod'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['amount', 'transaction_type', 'category_id'],
    title: 'TransactionCreate'
} as const;

export const TransactionResponseSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        },
        amount: {
            type: 'integer',
            title: 'Amount'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        transaction_date: {
            type: 'string',
            format: 'date-time',
            title: 'Transaction Date'
        },
        transaction_type: {
            '$ref': '#/components/schemas/TransactionType'
        },
        category_id: {
            type: 'integer',
            title: 'Category Id'
        },
        payment_method: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/PaymentMethod'
                },
                {
                    type: 'null'
                }
            ]
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        category: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/CategoryResponse'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['amount', 'transaction_date', 'transaction_type', 'category_id', 'user_id'],
    title: 'TransactionResponse'
} as const;

export const TransactionTypeSchema = {
    type: 'string',
    enum: ['income', 'expense'],
    title: 'TransactionType'
} as const;

export const TransactionUpdateSchema = {
    properties: {
        amount: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Amount'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        transaction_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Transaction Date'
        },
        transaction_type: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/TransactionType'
                },
                {
                    type: 'null'
                }
            ]
        },
        category_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category Id'
        },
        payment_method: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/PaymentMethod'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    title: 'TransactionUpdate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;