// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { CategoriesGetCategoriesData, CategoriesGetCategoriesResponse, CategoriesCreateCategoryData, CategoriesCreateCategoryResponse, CategoriesGetCategoryData, CategoriesGetCategoryResponse, CategoriesUpdateCategoryData, CategoriesUpdateCategoryResponse, CategoriesDeleteCategoryData, CategoriesDeleteCategoryResponse, ReadRootResponse, LoginGetAccessTokenData, LoginGetAccessTokenResponse, LoginPasswordRecoveryData, LoginPasswordRecoveryResponse, LoginResetPasswordData, LoginResetPasswordResponse, LoginRecoverPasswordHtmlContentData, LoginRecoverPasswordHtmlContentResponse, TransactionsGetTransactionsData, TransactionsGetTransactionsResponse, TransactionsCreateTransactionData, TransactionsCreateTransactionResponse, TransactionsGetTransactionData, TransactionsGetTransactionResponse, TransactionsUpdateTransactionData, TransactionsUpdateTransactionResponse, TransactionsDeleteTransactionData, TransactionsDeleteTransactionResponse, TransactionsGetCategorySpendingData, TransactionsGetCategorySpendingResponse, TransactionsGetMonthlyTrendsData, TransactionsGetMonthlyTrendsResponse, UsersGetUserMeResponse, UsersDeleteUserMeResponse, UsersUpdateUserMeData, UsersUpdateUserMeResponse, UsersUpdatePasswordMeData, UsersUpdatePasswordMeResponse, UsersRegisterUserData, UsersRegisterUserResponse, UsersGetUserData, UsersGetUserResponse, UsersGetUser1Data, UsersGetUser1Response, UsersUpdateUserData, UsersUpdateUserResponse, UsersDeleteUserData, UsersDeleteUserResponse } from './types.gen';

export class CategoriesService {
    /**
     * Get Categories
     * 전체 카테고리 조회
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns CategoryPaginatedResponse Successful Response
     * @throws ApiError
     */
    public static getCategories(data: CategoriesGetCategoriesData = {}): CancelablePromise<CategoriesGetCategoriesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/categories/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Category
     * 카테고리 생성
     * @param data The data for the request.
     * @param data.requestBody
     * @returns CategoryResponse Successful Response
     * @throws ApiError
     */
    public static createCategory(data: CategoriesCreateCategoryData): CancelablePromise<CategoriesCreateCategoryResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/categories/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Category
     * 특정 카테고리 조회
     * @param data The data for the request.
     * @param data.categoryId
     * @returns CategoryResponse Successful Response
     * @throws ApiError
     */
    public static getCategory(data: CategoriesGetCategoryData): CancelablePromise<CategoriesGetCategoryResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/categories/{category_id}',
            path: {
                category_id: data.categoryId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Category
     * 카테고리 수정
     * @param data The data for the request.
     * @param data.categoryId
     * @param data.requestBody
     * @returns CategoryResponse Successful Response
     * @throws ApiError
     */
    public static updateCategory(data: CategoriesUpdateCategoryData): CancelablePromise<CategoriesUpdateCategoryResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/categories/{category_id}',
            path: {
                category_id: data.categoryId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Category
     * 카테고리 삭제
     * @param data The data for the request.
     * @param data.categoryId
     * @returns void Successful Response
     * @throws ApiError
     */
    public static deleteCategory(data: CategoriesDeleteCategoryData): CancelablePromise<CategoriesDeleteCategoryResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/categories/{category_id}',
            path: {
                category_id: data.categoryId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class DefaultService {
    /**
     * Read Root
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static readRoot(): CancelablePromise<ReadRootResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/'
        });
    }
}

export class LoginService {
    /**
     * Get Access Token
     * @param data The data for the request.
     * @param data.formData
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static getAccessToken(data: LoginGetAccessTokenData): CancelablePromise<LoginGetAccessTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/access-token',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Password Recovery
     * 비밀번호 찾기
     * @param data The data for the request.
     * @param data.email
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static passwordRecovery(data: LoginPasswordRecoveryData): CancelablePromise<LoginPasswordRecoveryResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/password-recovery/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Reset Password
     * 비밀번호 초기화
     * @param data The data for the request.
     * @param data.requestBody
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static resetPassword(data: LoginResetPasswordData): CancelablePromise<LoginResetPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/reset-password/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Recover Password Html Content
     * HTML Content for Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns string Successful Response
     * @throws ApiError
     */
    public static recoverPasswordHtmlContent(data: LoginRecoverPasswordHtmlContentData): CancelablePromise<LoginRecoverPasswordHtmlContentResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/password-recovery-html-content/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class TransactionsService {
    /**
     * Get Transactions
     * 전체 거래내역 조회
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns TransactionPaginatedResponse Successful Response
     * @throws ApiError
     */
    public static getTransactions(data: TransactionsGetTransactionsData = {}): CancelablePromise<TransactionsGetTransactionsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/transactions/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Transaction
     * 거래내역 생성
     * @param data The data for the request.
     * @param data.requestBody
     * @returns TransactionResponse Successful Response
     * @throws ApiError
     */
    public static createTransaction(data: TransactionsCreateTransactionData): CancelablePromise<TransactionsCreateTransactionResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/transactions/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Transaction
     * 특정 거래내역 조회
     * @param data The data for the request.
     * @param data.transactionId
     * @returns TransactionResponse Successful Response
     * @throws ApiError
     */
    public static getTransaction(data: TransactionsGetTransactionData): CancelablePromise<TransactionsGetTransactionResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/transactions/{transaction_id}',
            path: {
                transaction_id: data.transactionId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Transaction
     * 거래내역 수정
     * @param data The data for the request.
     * @param data.transactionId
     * @param data.requestBody
     * @returns TransactionResponse Successful Response
     * @throws ApiError
     */
    public static updateTransaction(data: TransactionsUpdateTransactionData): CancelablePromise<TransactionsUpdateTransactionResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/transactions/{transaction_id}',
            path: {
                transaction_id: data.transactionId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Transaction
     * 거래내역 삭제
     * @param data The data for the request.
     * @param data.transactionId
     * @returns void Successful Response
     * @throws ApiError
     */
    public static deleteTransaction(data: TransactionsDeleteTransactionData): CancelablePromise<TransactionsDeleteTransactionResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/transactions/{transaction_id}',
            path: {
                transaction_id: data.transactionId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Category Spending
     * 카테고리별 지출 통계 (지출만, 상위 N개)
     * @param data The data for the request.
     * @param data.limit
     * @returns CategorySpending Successful Response
     * @throws ApiError
     */
    public static getCategorySpending(data: TransactionsGetCategorySpendingData = {}): CancelablePromise<TransactionsGetCategorySpendingResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/transactions/statistics/category-spending',
            query: {
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Monthly Trends
     * 월별 수입/지출 추이 (최근 N개월)
     * @param data The data for the request.
     * @param data.months
     * @returns MonthlyTrend Successful Response
     * @throws ApiError
     */
    public static getMonthlyTrends(data: TransactionsGetMonthlyTrendsData = {}): CancelablePromise<TransactionsGetMonthlyTrendsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/transactions/statistics/monthly-trends',
            query: {
                months: data.months
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UsersService {
    /**
     * Get User Me
     * 나의 계정 조회
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static getUserMe(): CancelablePromise<UsersGetUserMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Delete User Me
     * 나의 계정 삭제
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Update User Me
     * 나의 계정 수정
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUserMe(data: UsersUpdateUserMeData): CancelablePromise<UsersUpdateUserMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Password Me
     * 나의 비밀번호 수정
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static updatePasswordMe(data: UsersUpdatePasswordMeData): CancelablePromise<UsersUpdatePasswordMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me/password',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Register User
     * 회원가입
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static registerUser(data: UsersRegisterUserData): CancelablePromise<UsersRegisterUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/signup',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get User
     * 사용자 리스트 조회
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static getUser(data: UsersGetUserData = {}): CancelablePromise<UsersGetUserResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get User
     * 사용자 조회
     * @param data The data for the request.
     * @param data.userId
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static getUser1(data: UsersGetUser1Data): CancelablePromise<UsersGetUser1Response> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update User
     * 사용자 수정
     * @param data The data for the request.
     * @param data.userId
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUser(data: UsersUpdateUserData): CancelablePromise<UsersUpdateUserResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete User
     * 사용자 삭제
     * @param data The data for the request.
     * @param data.userId
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static deleteUser(data: UsersDeleteUserData): CancelablePromise<UsersDeleteUserResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}