// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type CategoryCreate = {
    name: string;
    description: string;
};

export type CategoryPublic = {
    created_at: string;
    updated_at?: (string | null);
    id: number;
    name: string;
    description: string;
};

export type CategoryUpdate = {
    name?: (string | null);
    description?: (string | null);
};

export type TransactionPublic = {
    id: number;
    amount: number;
    description?: (string | null);
    transaction_date: string;
    transaction_type: string;
    category_id: number;
    payment_method?: (string| null);
}

export type TransactionCreate = {
    amount: number;
    description?: (string | null);
    transaction_date: string;
    transaction_type: string;
    category_id: number;
    payment_method?: (string| null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

/**
 * Predicted tags based on user behavior
 */
export type TagPrediction = {
    predicted_tags: Array<(string)>;
    confidence_scores: {
        [key: string]: (number);
    };
    based_on_items: number;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

/**
 * Insights about user behavior patterns
 */
export type UserBehaviorInsights = {
    total_items: number;
    total_comments: number;
    most_active_hour: number;
    most_active_day: number;
    top_tags: Array<(string)>;
    average_items_per_day: number;
    predicted_next_tags: Array<(string)>;
    activity_trend: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type AnalyticsGetUserBehaviorInsightsResponse = (UserBehaviorInsights);

export type AnalyticsPredictNextTagsResponse = (TagPrediction);

export type AnalyticsTrackUserActivityData = {
    activityType: string;
    itemId?: (string | null);
    requestBody?: ({
    [key: string]: unknown;
} | null);
};

export type AnalyticsTrackUserActivityResponse = (unknown);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type CategoriesReadCategoriesData = {
    limit?: number;
    skip?: number;
};

export type CategoriesReadCategoriesResponse = (Array<CategoryPublic>);

export type CategoriesCreateCategoryData = {
    requestBody: CategoryCreate;
};

export type CategoriesCreateCategoryResponse = (CategoryPublic);

export type CategoriesReadCategoryData = {
    categoryId: number;
};

export type CategoriesReadCategoryResponse = (CategoryPublic);

export type CategoriesUpdateCategoryData = {
    categoryId: number;
    requestBody: CategoryUpdate;
};

export type CategoriesUpdateCategoryResponse = (CategoryPublic);

export type CategoriesDeleteCategoryData = {
    categoryId: number;
};

export type CategoriesDeleteCategoryResponse = (void);

export type TransactionsReadTransactionsData = {
    limit?: number;
    skip?: number;
};

export type TransactionsReadTransactionsResonse = (Array<TransactionPublic>);


export type TransactionsCreateTransactionsData = {
    requestBody: TransactionCreate;
};

export type TransactionsCreateTransactionsResonse = (TransactionPublic);