// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_get_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type CategoryCreate = {
    name: string;
    description: string;
};

export type CategoryPaginatedResponse = {
    items: Array<CategoryResponse>;
    total: number;
};

export type CategoryResponse = {
    name: string;
    description: string;
    id: number;
    created_at: string;
    updated_at?: (string | null);
};

export type CategorySpending = {
    category_id: number;
    category_name: string;
    total_amount: number;
    transaction_count: number;
};

export type CategoryUpdate = {
    name?: (string | null);
    description?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Message = {
    message: string;
};

export type MonthlyTrend = {
    year: number;
    month: number;
    income: number;
    expense: number;
    net: number;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PasswordUpdate = {
    current_password: string;
    new_password: string;
};

export type PaymentMethod = 'cash' | 'card';

export type Token = {
    access_token: string;
    token_type?: string;
};

export type TransactionCreate = {
    amount: number;
    description?: (string | null);
    transaction_date?: string;
    transaction_type: TransactionType;
    category_id: number;
    payment_method?: (PaymentMethod | null);
};

export type TransactionPaginatedResponse = {
    items: Array<TransactionResponse>;
    total: number;
};

export type TransactionResponse = {
    amount: number;
    description?: (string | null);
    transaction_date: string;
    transaction_type: TransactionType;
    category_id: number;
    payment_method?: (PaymentMethod | null);
    id: number;
    created_at: string;
    updated_at?: (string | null);
    user_id: string;
    category?: (CategoryResponse | null);
};

export type TransactionType = 'income' | 'expense';

export type TransactionUpdate = {
    amount?: (number | null);
    description?: (string | null);
    transaction_date?: (string | null);
    transaction_type?: (TransactionType | null);
    category_id?: (number | null);
    payment_method?: (PaymentMethod | null);
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    created_at?: string;
    updated_at?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UserUpdate = {
    full_name?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type CategoriesGetCategoriesData = {
    limit?: number;
    skip?: number;
};

export type CategoriesGetCategoriesResponse = (CategoryPaginatedResponse);

export type CategoriesCreateCategoryData = {
    requestBody: CategoryCreate;
};

export type CategoriesCreateCategoryResponse = (CategoryResponse);

export type CategoriesGetCategoryData = {
    categoryId: number;
};

export type CategoriesGetCategoryResponse = (CategoryResponse);

export type CategoriesUpdateCategoryData = {
    categoryId: number;
    requestBody: CategoryUpdate;
};

export type CategoriesUpdateCategoryResponse = (CategoryResponse);

export type CategoriesDeleteCategoryData = {
    categoryId: number;
};

export type CategoriesDeleteCategoryResponse = (void);

export type ReadRootResponse = (unknown);

export type LoginGetAccessTokenData = {
    formData: Body_login_get_access_token;
};

export type LoginGetAccessTokenResponse = (Token);

export type LoginPasswordRecoveryData = {
    email: string;
};

export type LoginPasswordRecoveryResponse = (unknown);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (unknown);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type TransactionsGetTransactionsData = {
    limit?: number;
    skip?: number;
};

export type TransactionsGetTransactionsResponse = (TransactionPaginatedResponse);

export type TransactionsCreateTransactionData = {
    requestBody: TransactionCreate;
};

export type TransactionsCreateTransactionResponse = (TransactionResponse);

export type TransactionsGetTransactionData = {
    transactionId: number;
};

export type TransactionsGetTransactionResponse = (TransactionResponse);

export type TransactionsUpdateTransactionData = {
    requestBody: TransactionUpdate;
    transactionId: number;
};

export type TransactionsUpdateTransactionResponse = (TransactionResponse);

export type TransactionsDeleteTransactionData = {
    transactionId: number;
};

export type TransactionsDeleteTransactionResponse = (void);

export type TransactionsGetCategorySpendingData = {
    limit?: number;
};

export type TransactionsGetCategorySpendingResponse = (Array<CategorySpending>);

export type TransactionsGetMonthlyTrendsData = {
    months?: number;
};

export type TransactionsGetMonthlyTrendsResponse = (Array<MonthlyTrend>);

export type UsersGetUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (unknown);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdate;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: PasswordUpdate;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersGetUserData = {
    limit?: number;
    skip?: number;
};

export type UsersGetUserResponse = (Array<UserPublic>);

export type UsersGetUser1Data = {
    userId: string;
};

export type UsersGetUser1Response = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (unknown);