// Note: the `PrivateService` is only available when generating the client
// for local environments
import { OpenAPI } from "../../src/client"

OpenAPI.BASE = `${process.env.VITE_API_URL}`

// TODO: PrivateService is not currently generated by the API client
// This test utility needs to be updated or removed
export const createUser = async (_params: {
  email: string
  password: string
}) => {
  throw new Error("PrivateService not available - test utility needs update")
  // return await PrivateService.createUser({
  //   requestBody: {
  //     email,
  //     password,
  //     is_verified: true,
  //     full_name: "Test User",
  //   },
  // })
}
